const getters = {
  // sidebar: state => state.app.sidebar,
  language: state => state.app.language,
  size: state => state.app.size,
  device: state => state.app.device,
  visitedViews: state => state.tagsView.visitedViews,
  cachedViews: state => state.tagsView.cachedViews,
  token: state => state.user.token,
  avatar: state => state.user.avatar,
  name: state => state.user.name,
  introduction: state => state.user.introduction,
  roles: state => state.user.roles,
  permission_routes: state => state.permission.routes,
  account: state => state.user.account,
  accountInfo: state => state.user.accountInfo,
  web3: state => state.web3.web3,
  networkId: state => state.web3.networkId,
  web3Modal: state => state.web3.web3Modal,
}
export default getters
